`timescale 1 ns / 1 ps

/***************************************************************
 * Testbench for PicoRV32 AES + SHA-256 with BRAM Memory
 *
 * This version uses actual BRAM-based memory (synthesizable)
 * instead of testbench memory simulation.
 *
 * Memory is initialized from program.hex file generated by
 * generate_program_hex.py script.
 ***************************************************************/

module tb_picorv32_aes_bram;

    //=========================================================
    // Parameters
    //=========================================================
    parameter CLK_PERIOD = 10;          // 100 MHz clock
    parameter TIMEOUT_CYCLES = 100000;  // Max cycles before timeout

    //=========================================================
    // Clock and Reset
    //=========================================================
    reg clk = 1;
    reg resetn = 0;
    wire trap;

    always #(CLK_PERIOD/2) clk = ~clk;

    //=========================================================
    // VCD Dump
    //=========================================================
    initial begin
        $dumpfile("tb_picorv32_aes_bram.vcd");
        $dumpvars(0, tb_picorv32_aes_bram);
    end

    //=========================================================
    // 8-Lane Parallel SPI Interface
    //=========================================================
    wire [7:0] aes_spi_data;
    wire       aes_spi_clk;
    wire       aes_spi_cs_n;
    wire       aes_spi_active;

    //=========================================================
    // Memory Interface (connects CPU to BRAM)
    //=========================================================
    wire        mem_valid;
    wire        mem_instr;
    wire        mem_ready;
    wire [31:0] mem_addr;
    wire [31:0] mem_wdata;
    wire [3:0]  mem_wstrb;
    wire [31:0] mem_rdata;

    //=========================================================
    // PicoRV32 CPU Instance
    //=========================================================
    picorv32 #(
        .ENABLE_COUNTERS(1),
        .ENABLE_REGS_16_31(1),
        .ENABLE_REGS_DUALPORT(1),
        .LATCHED_MEM_RDATA(0),
        .TWO_STAGE_SHIFT(1),
        .TWO_CYCLE_COMPARE(0),
        .TWO_CYCLE_ALU(0),
        .CATCH_MISALIGN(1),
        .CATCH_ILLINSN(1),
        .ENABLE_PCPI(1),
        .ENABLE_MUL(1),
        .ENABLE_DIV(1),
        .ENABLE_FAST_MUL(1),
        .ENABLE_IRQ(0),
        .ENABLE_IRQ_QREGS(0),
        // **Enable AES encryption co-processor**
        .ENABLE_AES(1),
        .ENABLE_AES_DEC(1),
        // **Enable SHA-256 hash co-processor**
        .ENABLE_SHA256(1)
    ) cpu (
        .clk         (clk),
        .resetn      (resetn),
        .trap        (trap),

        // Memory Interface
        .mem_valid   (mem_valid),
        .mem_instr   (mem_instr),
        .mem_ready   (mem_ready),
        .mem_addr    (mem_addr),
        .mem_wdata   (mem_wdata),
        .mem_wstrb   (mem_wstrb),
        .mem_rdata   (mem_rdata),

        // 8-Lane Parallel SPI Interface
        .aes_spi_data   (aes_spi_data),
        .aes_spi_clk    (aes_spi_clk),
        .aes_spi_cs_n   (aes_spi_cs_n),
        .aes_spi_active (aes_spi_active)
    );

    //=========================================================
    // BRAM Memory Instance
    //=========================================================
    bram_memory #(
        .MEM_SIZE_WORDS(2048),           // 8 KB memory
        .MEM_INIT_FILE("program.hex")    // Load from hex file
    ) mem (
        .clk        (clk),
        .resetn     (resetn),
        .mem_valid  (mem_valid),
        .mem_instr  (mem_instr),
        .mem_ready  (mem_ready),
        .mem_addr   (mem_addr),
        .mem_wdata  (mem_wdata),
        .mem_wstrb  (mem_wstrb),
        .mem_rdata  (mem_rdata)
    );

    //=========================================================
    // Test Control
    //=========================================================
    reg [31:0] cycle_count = 0;
    reg [127:0] expected_ciphertext = 128'h69c4e0d86a7b0430d8cdb78070b4c55a;

    // 8-Lane SPI Capture (24 bytes: 16 CT + 8-byte auth tag)
    reg [7:0]  spi_received_bytes [0:23];
    reg [4:0]  spi_byte_count = 0;
    reg        spi_prev_clk = 0;
    reg        spi_prev_cs_n = 1;
    reg        spi_transfer_complete = 0;
    reg [127:0] received_ciphertext;
    reg [63:0] received_tag;
    reg [63:0] expected_tag = 64'hef9935f981202cd6;

    // Decryption Result Tracking
    reg [127:0] expected_plaintext = 128'h00112233445566778899aabbccddeeff;
    reg [31:0]  match_result;
    reg         match_result_valid = 0;
    reg [31:0]  dec_word0, dec_word1, dec_word2, dec_word3;

    // SHA-256 Result Tracking
    reg [31:0]  sha_digest [0:7];
    reg [31:0]  sha_match_result;
    reg         sha_match_valid = 0;

    //=========================================================
    // Cycle Counter
    //=========================================================
    always @(posedge clk) begin
        if (resetn)
            cycle_count <= cycle_count + 1;
    end

    //=========================================================
    // 8-Lane Parallel SPI Capture
    //=========================================================
    always @(posedge clk) begin
        spi_prev_clk <= aes_spi_clk;
        spi_prev_cs_n <= aes_spi_cs_n;

        // Start of transfer
        if (!aes_spi_cs_n && spi_prev_cs_n) begin
            spi_byte_count <= 0;
            spi_transfer_complete <= 0;
            $display("[Cycle %0d] SPI Transfer Started", cycle_count);
        end

        // End of transfer
        if (aes_spi_cs_n && !spi_prev_cs_n) begin
            spi_transfer_complete <= 1;
            $display("[Cycle %0d] SPI Transfer Complete (%0d bytes)", cycle_count, spi_byte_count);

            // Reconstruct ciphertext from bytes 0-15 (little-endian)
            received_ciphertext = {
                spi_received_bytes[15], spi_received_bytes[14],
                spi_received_bytes[13], spi_received_bytes[12],
                spi_received_bytes[11], spi_received_bytes[10],
                spi_received_bytes[9],  spi_received_bytes[8],
                spi_received_bytes[7],  spi_received_bytes[6],
                spi_received_bytes[5],  spi_received_bytes[4],
                spi_received_bytes[3],  spi_received_bytes[2],
                spi_received_bytes[1],  spi_received_bytes[0]
            };

            // Reconstruct 64-bit auth tag from bytes 16-23 (big-endian)
            received_tag = {
                spi_received_bytes[16], spi_received_bytes[17],
                spi_received_bytes[18], spi_received_bytes[19],
                spi_received_bytes[20], spi_received_bytes[21],
                spi_received_bytes[22], spi_received_bytes[23]
            };
        end

        // Capture data on rising edge
            if (!aes_spi_cs_n && aes_spi_clk && !spi_prev_clk) begin
            spi_received_bytes[spi_byte_count] <= aes_spi_data;
            if (spi_byte_count < 16)
                $display("  SPI CT  Byte[%2d] = 0x%02x", spi_byte_count, aes_spi_data);
            else
                $display("  SPI TAG Byte[%2d] = 0x%02x", spi_byte_count, aes_spi_data);
            spi_byte_count <= spi_byte_count + 1;
        end
    end

    //=========================================================
    // Memory Write Monitor (Decryption + SHA-256 Results)
    //=========================================================
    always @(posedge clk) begin
        if (mem_valid && mem_ready && |mem_wstrb) begin
            case (mem_addr)
                // Decryption match result (MATCH_ADDR = 0x330)
                32'h00000330: begin
                    match_result <= mem_wdata;
                    match_result_valid <= 1;
                    $display("[Cycle %0d] Decryption match result written: %0d", cycle_count, mem_wdata);
                end
                // Decrypted plaintext (DEC_RESULT_ADDR = 0x340)
                32'h00000340: dec_word0 <= mem_wdata;
                32'h00000344: dec_word1 <= mem_wdata;
                32'h00000348: dec_word2 <= mem_wdata;
                32'h0000034C: dec_word3 <= mem_wdata;

                // SHA-256 digest words (SHA_DIGEST_ADDR = 0x440)
                32'h00000440: begin sha_digest[0] <= mem_wdata; $display("[Cycle %0d] SHA digest[0] = 0x%08x", cycle_count, mem_wdata); end
                32'h00000444: begin sha_digest[1] <= mem_wdata; $display("[Cycle %0d] SHA digest[1] = 0x%08x", cycle_count, mem_wdata); end
                32'h00000448: begin sha_digest[2] <= mem_wdata; $display("[Cycle %0d] SHA digest[2] = 0x%08x", cycle_count, mem_wdata); end
                32'h0000044C: begin sha_digest[3] <= mem_wdata; $display("[Cycle %0d] SHA digest[3] = 0x%08x", cycle_count, mem_wdata); end
                32'h00000450: begin sha_digest[4] <= mem_wdata; $display("[Cycle %0d] SHA digest[4] = 0x%08x", cycle_count, mem_wdata); end
                32'h00000454: begin sha_digest[5] <= mem_wdata; $display("[Cycle %0d] SHA digest[5] = 0x%08x", cycle_count, mem_wdata); end
                32'h00000458: begin sha_digest[6] <= mem_wdata; $display("[Cycle %0d] SHA digest[6] = 0x%08x", cycle_count, mem_wdata); end
                32'h0000045C: begin sha_digest[7] <= mem_wdata; $display("[Cycle %0d] SHA digest[7] = 0x%08x", cycle_count, mem_wdata); end

                // SHA-256 match result (SHA_MATCH_ADDR = 0x460)
                32'h00000460: begin
                    sha_match_result <= mem_wdata;
                    sha_match_valid <= 1;
                    $display("[Cycle %0d] SHA match result written: %0d", cycle_count, mem_wdata);
                end
            endcase
        end
    end

    //=========================================================
    // Trap Monitor
    //=========================================================
    always @(posedge clk) begin
        if (trap) begin
            $display("");
            $display("!!! TRAP detected at cycle %0d !!!", cycle_count);
            $display("!!! This indicates an illegal instruction or error !!!");
            $display("");
            #100;
            $finish;
        end
    end

    //=========================================================
    // Main Test Sequence
    //=========================================================
    initial begin : main_test
        integer i;
        reg [127:0] decrypted_plaintext;
        reg all_passed;

        $display("================================================================");
        $display("  PicoRV32 Full Pipeline Test (Encrypt + Decrypt + SHA-256)");
        $display("================================================================");
        $display("");
        $display("Configuration:");
        $display("  - Memory: BRAM-based (synthesizable)");
        $display("  - Init File: program.hex");
        $display("  - Clock: %0d MHz", 1000/CLK_PERIOD);
        $display("  - Pipeline: Encrypt -> SHA-256(CT||KEY) -> SPI(CT+Tag64) -> Decrypt -> SHA-256 Verify");
        $display("");

        all_passed = 1;

        // Initialize SPI capture (24 bytes: 16 CT + 8-byte tag)
        for (i = 0; i < 24; i = i + 1)
            spi_received_bytes[i] = 8'h00;
        for (i = 0; i < 8; i = i + 1)
            sha_digest[i] = 32'h0;

        // Reset sequence
        repeat (20) @(posedge clk);
        resetn <= 1;
        $display("[Cycle 0] Reset released - CPU starting");
        $display("");

        // Wait for full pipeline completion or timeout
        fork
            begin : wait_pipeline
                // === Phase 1: Encryption + SPI ===
                wait(spi_transfer_complete == 1);

                repeat (10) @(posedge clk);

                $display("");
                $display("================================================================");
                $display("  SPI Transfer Complete - Verifying Encryption + SHA-256 Hash");
                $display("================================================================");
                $display("");
                $display("Received Ciphertext (SPI bytes 0-15):  0x%032x", received_ciphertext);
                $display("Expected Ciphertext:                   0x%032x", expected_ciphertext);
                $display("");
                $display("Received Auth Tag (SPI bytes 16-23): 0x%016x", received_tag);
                $display("Expected Auth Tag:                   0x%016x", expected_tag);

                if (received_ciphertext == expected_ciphertext) begin
                    $display("");
                    $display("*** ENCRYPTION SPI TEST PASSED ***");
                end else begin
                    $display("");
                    $display("*** ENCRYPTION SPI TEST FAILED ***");
                    all_passed = 0;
                end

                if (received_tag == expected_tag) begin
                    $display("*** AUTH TAG SPI TEST PASSED ***");
                end else begin
                    $display("*** AUTH TAG SPI TEST FAILED ***");
                    all_passed = 0;
                end

                // === Phase 2: Decryption ===
                wait(match_result_valid == 1);

                repeat (10) @(posedge clk);

                // Assemble decrypted plaintext from captured words
                decrypted_plaintext = {dec_word3, dec_word2, dec_word1, dec_word0};

                $display("");
                $display("================================================================");
                $display("  Decryption Complete - Verifying Results");
                $display("================================================================");
                $display("");
                $display("Decrypted Plaintext: 0x%032x", decrypted_plaintext);
                $display("Original Plaintext:  0x%032x", expected_plaintext);

                if (match_result == 32'd1) begin
                    $display("");
                    $display("*** DECRYPTION TEST PASSED ***");
                end else begin
                    $display("");
                    $display("*** DECRYPTION TEST FAILED ***");
                    $display("  Match result: %0d (expected 1)", match_result);
                    all_passed = 0;
                end

                // === Phase 3: SHA-256 ===
                wait(sha_match_valid == 1);

                repeat (10) @(posedge clk);

                $display("");
                $display("================================================================");
                $display("  SHA-256 Complete - Verifying Software Hash of (Ciphertext||Key)");
                $display("================================================================");
                $display("");
                $display("SHA-256 Digest (of ciphertext||key):");
                $display("  H[0] = 0x%08x  (expected 0xef9935f9)", sha_digest[0]);
                $display("  H[1] = 0x%08x  (expected 0x81202cd6)", sha_digest[1]);
                $display("  H[2] = 0x%08x  (expected 0x03abb02b)", sha_digest[2]);
                $display("  H[3] = 0x%08x  (expected 0xe19e63f6)", sha_digest[3]);
                $display("  H[4] = 0x%08x  (expected 0xf70c98af)", sha_digest[4]);
                $display("  H[5] = 0x%08x  (expected 0x66e41670)", sha_digest[5]);
                $display("  H[6] = 0x%08x  (expected 0xfe203af0)", sha_digest[6]);
                $display("  H[7] = 0x%08x  (expected 0xeace13b8)", sha_digest[7]);

                if (sha_match_result == 32'd1) begin
                    $display("");
                    $display("*** SHA-256 TEST PASSED ***");
                end else begin
                    $display("");
                    $display("*** SHA-256 TEST FAILED ***");
                    $display("  Match result: %0d (expected 1)", sha_match_result);
                    all_passed = 0;
                end

                // === Final Verdict ===
                $display("");
                $display("================================================================");
                if (all_passed) begin
                    $display("  *** FULL PIPELINE PASSED ***");
                end else begin
                    $display("  *** PIPELINE TEST FAILED ***");
                end
                $display("================================================================");
                $display("");

                #1000;
                $finish;
            end

            begin : timeout
                repeat (TIMEOUT_CYCLES) @(posedge clk);
                $display("");
                $display("================================================================");
                $display("  *** TIMEOUT - Test did not complete ***");
                $display("================================================================");
                $display("  Cycles elapsed: %0d", TIMEOUT_CYCLES);
                $display("  SPI complete: %0b", spi_transfer_complete);
                $display("  Decrypt result valid: %0b", match_result_valid);
                $display("  SHA match valid: %0b", sha_match_valid);
                $display("");
                $finish;
            end
        join
    end

endmodule
