`timescale 1 ns / 1 ps

/***************************************************************
 * Testbench for PicoRV32 AES with BRAM Memory
 *
 * This version uses actual BRAM-based memory (synthesizable)
 * instead of testbench memory simulation.
 *
 * Memory is initialized from program.hex file generated by
 * generate_program_hex.py script.
 ***************************************************************/

module tb_picorv32_aes_bram;

    //=========================================================
    // Parameters
    //=========================================================
    parameter CLK_PERIOD = 10;          // 100 MHz clock
    parameter TIMEOUT_CYCLES = 100000;  // Max cycles before timeout

    //=========================================================
    // Clock and Reset
    //=========================================================
    reg clk = 1;
    reg resetn = 0;
    wire trap;

    always #(CLK_PERIOD/2) clk = ~clk;

    //=========================================================
    // VCD Dump
    //=========================================================
    initial begin
        $dumpfile("tb_picorv32_aes_bram.vcd");
        $dumpvars(0, tb_picorv32_aes_bram);
    end

    //=========================================================
    // 8-Lane Parallel SPI Interface
    //=========================================================
    wire [7:0] aes_spi_data;
    wire       aes_spi_clk;
    wire       aes_spi_cs_n;
    wire       aes_spi_active;

    //=========================================================
    // Memory Interface (connects CPU to BRAM)
    //=========================================================
    wire        mem_valid;
    wire        mem_instr;
    wire        mem_ready;
    wire [31:0] mem_addr;
    wire [31:0] mem_wdata;
    wire [3:0]  mem_wstrb;
    wire [31:0] mem_rdata;

    //=========================================================
    // PicoRV32 CPU Instance
    //=========================================================
    picorv32 #(
        .ENABLE_COUNTERS(1),
        .ENABLE_REGS_16_31(1),
        .ENABLE_REGS_DUALPORT(1),
        .LATCHED_MEM_RDATA(0),
        .TWO_STAGE_SHIFT(1),
        .TWO_CYCLE_COMPARE(0),
        .TWO_CYCLE_ALU(0),
        .CATCH_MISALIGN(1),
        .CATCH_ILLINSN(1),
        .ENABLE_PCPI(1),
        .ENABLE_MUL(1),
        .ENABLE_DIV(1),
        .ENABLE_FAST_MUL(1),
        .ENABLE_IRQ(0),
        .ENABLE_IRQ_QREGS(0),
        // **Enable AES encryption co-processor**
        .ENABLE_AES(1),
        .ENABLE_AES_DEC(1)
    ) cpu (
        .clk         (clk),
        .resetn      (resetn),
        .trap        (trap),

        // Memory Interface
        .mem_valid   (mem_valid),
        .mem_instr   (mem_instr),
        .mem_ready   (mem_ready),
        .mem_addr    (mem_addr),
        .mem_wdata   (mem_wdata),
        .mem_wstrb   (mem_wstrb),
        .mem_rdata   (mem_rdata),

        // 8-Lane Parallel SPI Interface
        .aes_spi_data   (aes_spi_data),
        .aes_spi_clk    (aes_spi_clk),
        .aes_spi_cs_n   (aes_spi_cs_n),
        .aes_spi_active (aes_spi_active)
    );

    //=========================================================
    // BRAM Memory Instance
    //=========================================================
    bram_memory #(
        .MEM_SIZE_WORDS(2048),           // 8 KB memory
        .MEM_INIT_FILE("program.hex")    // Load from hex file
    ) mem (
        .clk        (clk),
        .resetn     (resetn),
        .mem_valid  (mem_valid),
        .mem_instr  (mem_instr),
        .mem_ready  (mem_ready),
        .mem_addr   (mem_addr),
        .mem_wdata  (mem_wdata),
        .mem_wstrb  (mem_wstrb),
        .mem_rdata  (mem_rdata)
    );

    //=========================================================
    // Test Control
    //=========================================================
    reg [31:0] cycle_count = 0;
    reg [127:0] expected_ciphertext = 128'h69c4e0d86a7b0430d8cdb78070b4c55a;

    // 8-Lane SPI Capture
    reg [7:0]  spi_received_bytes [0:15];
    reg [4:0]  spi_byte_count = 0;
    reg        spi_prev_clk = 0;
    reg        spi_prev_cs_n = 1;
    reg        spi_transfer_complete = 0;
    reg [127:0] received_ciphertext;

    // Decryption Result Tracking
    reg [127:0] expected_plaintext = 128'h00112233445566778899aabbccddeeff;
    reg [31:0]  match_result;
    reg         match_result_valid = 0;
    reg [31:0]  dec_word0, dec_word1, dec_word2, dec_word3;

    //=========================================================
    // Cycle Counter
    //=========================================================
    always @(posedge clk) begin
        if (resetn)
            cycle_count <= cycle_count + 1;
    end

    //=========================================================
    // 8-Lane Parallel SPI Capture
    //=========================================================
    always @(posedge clk) begin
        spi_prev_clk <= aes_spi_clk;
        spi_prev_cs_n <= aes_spi_cs_n;

        // Start of transfer
        if (!aes_spi_cs_n && spi_prev_cs_n) begin
            spi_byte_count <= 0;
            spi_transfer_complete <= 0;
            $display("[Cycle %0d] SPI Transfer Started", cycle_count);
        end

        // End of transfer
        if (aes_spi_cs_n && !spi_prev_cs_n) begin
            spi_transfer_complete <= 1;
            $display("[Cycle %0d] SPI Transfer Complete (%0d bytes)", cycle_count, spi_byte_count);

            // Reconstruct ciphertext
            received_ciphertext = {
                spi_received_bytes[15], spi_received_bytes[14],
                spi_received_bytes[13], spi_received_bytes[12],
                spi_received_bytes[11], spi_received_bytes[10],
                spi_received_bytes[9],  spi_received_bytes[8],
                spi_received_bytes[7],  spi_received_bytes[6],
                spi_received_bytes[5],  spi_received_bytes[4],
                spi_received_bytes[3],  spi_received_bytes[2],
                spi_received_bytes[1],  spi_received_bytes[0]
            };
        end

        // Capture data on rising edge
        if (!aes_spi_cs_n && aes_spi_clk && !spi_prev_clk) begin
            spi_received_bytes[spi_byte_count] <= aes_spi_data;
            $display("  SPI Byte[%2d] = 0x%02x", spi_byte_count, aes_spi_data);
            spi_byte_count <= spi_byte_count + 1;
        end
    end

    //=========================================================
    // Memory Write Monitor (Decryption Results)
    //=========================================================
    always @(posedge clk) begin
        if (mem_valid && mem_ready && |mem_wstrb) begin
            case (mem_addr)
                32'h00000500: begin
                    match_result <= mem_wdata;
                    match_result_valid <= 1;
                    $display("[Cycle %0d] Match result written: %0d", cycle_count, mem_wdata);
                end
                32'h00000600: dec_word0 <= mem_wdata;
                32'h00000604: dec_word1 <= mem_wdata;
                32'h00000608: dec_word2 <= mem_wdata;
                32'h0000060C: dec_word3 <= mem_wdata;
            endcase
        end
    end

    //=========================================================
    // Trap Monitor
    //=========================================================
    always @(posedge clk) begin
        if (trap) begin
            $display("");
            $display("!!! TRAP detected at cycle %0d !!!", cycle_count);
            $display("!!! This indicates an illegal instruction or error !!!");
            $display("");
            #100;
            $finish;
        end
    end

    //=========================================================
    // Main Test Sequence
    //=========================================================
    initial begin : main_test
        integer i;
        reg [127:0] decrypted_plaintext;

        $display("================================================================");
        $display("  PicoRV32 AES Full Pipeline Test (Encrypt + Decrypt)");
        $display("================================================================");
        $display("");
        $display("Configuration:");
        $display("  - Memory: BRAM-based (synthesizable)");
        $display("  - Init File: program.hex");
        $display("  - Clock: %0d MHz", 1000/CLK_PERIOD);
        $display("  - Pipeline: Encrypt -> SPI -> Decrypt -> Verify");
        $display("");

        // Initialize SPI capture
        for (i = 0; i < 16; i = i + 1)
            spi_received_bytes[i] = 8'h00;

        // Reset sequence
        repeat (20) @(posedge clk);
        resetn <= 1;
        $display("[Cycle 0] Reset released - CPU starting");
        $display("");

        // Wait for full pipeline completion or timeout
        fork
            begin : wait_pipeline
                // === Phase 1: Encryption + SPI ===
                wait(spi_transfer_complete == 1);

                repeat (10) @(posedge clk);

                $display("");
                $display("================================================================");
                $display("  SPI Transfer Complete - Verifying Encryption");
                $display("================================================================");
                $display("");
                $display("Received Ciphertext: 0x%032x", received_ciphertext);
                $display("Expected Ciphertext: 0x%032x", expected_ciphertext);

                if (received_ciphertext == expected_ciphertext) begin
                    $display("");
                    $display("*** ENCRYPTION TEST PASSED ***");
                end else begin
                    $display("");
                    $display("*** ENCRYPTION TEST FAILED ***");
                end

                // === Phase 2: Decryption ===
                wait(match_result_valid == 1);

                repeat (10) @(posedge clk);

                // Assemble decrypted plaintext from captured words
                decrypted_plaintext = {dec_word3, dec_word2, dec_word1, dec_word0};

                $display("");
                $display("================================================================");
                $display("  Decryption Complete - Verifying Results");
                $display("================================================================");
                $display("");
                $display("Decrypted Plaintext: 0x%032x", decrypted_plaintext);
                $display("Original Plaintext:  0x%032x", expected_plaintext);

                if (match_result == 32'd1) begin
                    $display("");
                    $display("*** DECRYPTION TEST PASSED ***");
                end else begin
                    $display("");
                    $display("*** DECRYPTION TEST FAILED ***");
                    $display("  Match result: %0d (expected 1)", match_result);
                end

                // === Final Verdict ===
                $display("");
                $display("================================================================");
                if (received_ciphertext == expected_ciphertext && match_result == 32'd1) begin
                    $display("  *** FULL PIPELINE PASSED ***");
                end else begin
                    $display("  *** PIPELINE TEST FAILED ***");
                end
                $display("================================================================");
                $display("");

                #1000;
                $finish;
            end

            begin : timeout
                repeat (TIMEOUT_CYCLES) @(posedge clk);
                $display("");
                $display("================================================================");
                $display("  *** TIMEOUT - Test did not complete ***");
                $display("================================================================");
                $display("  Cycles elapsed: %0d", TIMEOUT_CYCLES);
                $display("  SPI complete: %0b", spi_transfer_complete);
                $display("  Decrypt result valid: %0b", match_result_valid);
                $display("");
                $finish;
            end
        join
    end

endmodule
